var customer = (function(){
	var init = function(){
		onCreate();
	};
	
	var setContentView = function(){
	};
	
	var onCreate = function(){
		setContentView();
		$(".gnb li:nth-child(1)").click(function(){
			$("#pub_article").html(guide_form);
		 });
		
		$(".gnb li:nth-child(2)").click(function(){
			$("#pub_article").html(fare_form);
		 });
		
		$(".gnb li:nth-child(3)").click(function() {
			$('#pub_article').html(company_form);
		});
		
		$(".gnb li:nth-child(4)").click(function(){
			customer.notice_list(1);
			/*$.ajax({
				url : app.context() + '/customer/notice',
				type : 'GET',
				data : {},
				dataType : 'JSON',
				success : function(data){
					$("#pub_article").html(customer_notice_form);
					customer.init();
				},
				error : function(x, s, m){
					alert("고객센터 이동중 에러발생" + m);
				}
			})*/
		});
		
		$(".faq_lnb > li:nth-child(1)").click(function(){
			$.ajax({
				url : app.context() + '/customer/notice',
				type : 'GET',
				data : {},
				dataType : 'JSON',
				success : function(data){
					$("#pub_article").html(customer_notice_form);
				}
			});
		});
		
		$(".faq_lnb > li:nth-child(2)").click(function(){
			$.ajax({
				url : app.context() + '/customer/faq',
				type : 'GET',
				data : {},
				dataType : 'JSON',
				success : function(data){
					$("#pub_article").html(customer_faq_0_form);
					$(".faq .faq-list dt").click(function(){
						$(".faq .faq-list dt").removeClass('active');
						$(this).addClass('active');
						$(".faq .faq-list dd").not($(this).next("dd")).slideUp();
						$(this).next("dd").slideToggle();
						return false;
					});
				}
			});
		});
		$(".faq_lnb > li:nth-child(3)").click(function(){
			$.ajax({
				url : app.context() + '/customer/inquiry',
				type : 'GET',
				data : {},
				dataType : 'JSON',
				success : function(data){
					$("#pub_article").html(customer_inquiry_form);
				}
			});
		});
		
		$(".faq_lnb > li:nth-child(4)").click(function(){
			$.ajax({
				url : app.context() + '/customer/voc',
				type : 'GET',
				data : {},
				dataType : 'JSON',
				success : function(data){
					$("#pub_article").html(customer_voc_form);
				}
			});
		});
		
		$('.subj').click(function() {
			$.ajax({
				url : app.context() + '/customer/article',
				type : 'GET',
				data : {},
				dataType : 'JSON',
				success : function(data) {
					$('#pub_article').html(customer_notice_content_form);
				}
			});
		});
	};

	return{
		init : init,
		setContentView : setContentView,
		onCreate : onCreate,
		notice_list : function(pgNum){
			$.getJSON(app.context() + '/customer/list/' + pgNum, function(data){
				var frame = '';
				var startPg = data.startPg;
				var lastPg = data.lastPg;
				var pgSize = data.pgSize;
				var totPg = data.totPg;
				var groupSize = data.groupSize;
				console.log('스타트 페이지' + startPg);
				console.log('라스트 페이지' + lastPg);
				console.log('페이지 사이즈' + pgSize);
				console.log('토탈 페이지' + totPg);
				console.log('그룹 사이즈' + groupSize);
				var notice_list = 
					'<div id= "customer" class="notice1">'
					+'<div id="container" class="box">'
					+'<div id="content">'
					+'<h2><img src="resources/img/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
					+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
					+'<div class="faq_lnb">'
					+'<ul class="faq_lnb">'
					+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
					+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
					+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
					+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
					+'</ul>'
					+'<div class="section1">'
					+'<h3><img src="'+app.img()+'/h3_notice.gif" alt="공지사항"></h3>'
					+'<div class="notice-search">'
					+'<form name="search" method="post" action="">'
					+'<fieldset>'
					+'<input type="text" class="input">'
					+'<input id="btn_search" type="image" src="'+app.img()+'/btn_notice_search.gif" alt="검색">'
					+'</fieldset>'
					+'</form>'
					+'</div>'
					+'<table cellspacing="0" summary="공지사항" class="cols">'
					+'<colgroup><col width="65"><col><col width="105"></colgroup>'
					+'<thead>'
					+'<tr>'
					+'<th>번호</th>'
					+'<th>제목</th>'
					+'<th>작성일</th>'
					+'</tr>'
					+'</thead>'
					+'<tbody>';
				if (data.totCount == 0){
					notice += '<tr><td colspan=3>등록된 공지사항이 없습니다.</td></tr>';
				} else {
					$.each(data.list, function(i, customer){
						notice_list += 
							 '<tr>'
							+'<td>' + customer.customerSeq + '</td>'
							+'<td style="text-align: left"><a>' + customer.title + '</a></td>'
							+'<td>' + customer.regDate + '</td>'
							+'<tr>';
							
					}); //else 의 $.each 끝
				}
				notice_list += '</tbody></table>';
				var pagination = 
					 '<nav aria-label="Page navigation">'
					+'<ul class="paginate">';
				$('#pub_article').html(notice_list);
				if((startPg - pgSize) > 0){
					var temp = startPg - pgSize;
					pagination +=
						 '<li style="float: left">'
						+'<a onclick="customer.notice_list(' + temp + ')" aria-label="Previous">'
						+'<span aria-hidden="true">&laquo;</span>'
						+'</a>'
						+'</li>';
				}
				for(var i=startPg; i<=lastPg; i++){
					if(i == pgNum){
						pagination += '<font color="blue"><strong>' + i + '</strong></font>';
					} else {
						pagination += '<a onclick="customer.notice_list('+ i +')">' + ' ' + i + ' ' + '</a>';
					}
				}
				if(startPg + pgSize <= totPg){
					var temp = startPg + pgSize;
					pagination += 
						 '<li style="float: right">'
						+'<a onclick="customer.notice_list(' + temp + ')" aria-label="Next">'
						+'<span aria-hidden="true">&raquo;</span>'
						+'</a>'
						+'</li>';
				}
				pagination += '</ul></nav>';
				frame += notice_list;
				frame += pagination;
				$('#pub_article').html(frame);
			}); // notice_list의 getJSON 끝
		}	//notice_list 끝
	}
})();

var customer_faq_0_form =
	'<div id= "customer" class="faq">'
	+'<div id="container" class="box">'
	+'<div id="content">'
	+'<h2><img src="'+app.img()+'/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
	+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
	+'<div class="faq_lnb">'
	+'<ul class="faq_lnb">'
	+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
	+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
	+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
	+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
	+'</ul>'
	+'<div class="section1">'
	+'<h3><img src="http://socdnw.speedgabia.com/template/asset/images/customer/h3_faq.gif" alt="자주묻는 질문"></h3>'
	+'<div class="search-box">'
	+'<form class="faq_form" name="search" method="post" action="">'
	+'<fieldset>'
	+'<select>'
	+'<option selected="selected">전체</option>'
	+'</select>'
	+'<input type="text" class="input">'
	+'<input id="btn_search" type="image" class="submit" src="http://socdnw.speedgabia.com/template/asset/images/customer/btn_faq_search.gif" alt="검색">'
	+'</fieldset>'
	+'</form>'
	+'</div>'
	+'<form class="faq_form" name="faq" method="post" action="">'
	+'<fieldset>'
	+'<div class="tab">'
	+'<ul>'
	+'<li class="on"><a href="${context}/admin/faq_0" class="btn_category tab1 0">자주묻는 질문</a></li>'
	+'<li><a href="${context}/admin/faq_1" class="btn_category tab2 1">예약/결제문의</a></li>'
	+'<li><a href="${context}/admin/faq_2" class="btn_category tab3 2">가입문의</a></li>'
	+'<li><a href="${context}/admin/faq_3" class="btn_category tab4 3">차량이용/사고</a></li>'
	+'<li><a href="${context}/admin/faq_4" class="btn_category tab5 4">프로모션/쿠폰</a></li>'
	+'<li><a href="${context}/admin/faq_5" class="btn_category tab6 5">법인/단체</a></li>'
	+'<li><a href="${context}/admin/faq_6" class="btn_category tab7 6">탈퇴</a></li>'
	+'<li><a href="${context}/admin/faq_7" class="btn_category tab8 7">기타</a></li>'
	+'</ul>'
	+'</div>'
	+'<p class="count">총게시물 <strong>10</strong>개</p>'
	+'<dl class="faq-list">'
	+'<dt name="#faq1" class="active"><span>Q</span> 세차가 하고 싶어요! 어떻게 해야하나요?</dt>'
	+'<dd style="display: none;"><span>A</span>'
	+'이용 중 세차가 하고 싶으신가요? 자비부담으로 세차 진행 시 1만 크레딧으로 리워드 해드립니다. 이용 중인 차량의 스마트키 &gt; 추가 기능 사용하기 &gt; 세차 인증 메뉴에서 세차 전후 사진을 촬영하여 남겨주세요!<br><br>'
	+'※ 담당자 확인 후 크레딧 지급까지 3~4일이 소요됩니다.<br><br>'
	+'자세한 사항은 아래 링크를 참고하세요. <br><br>'
	+'<a href="http://www.socar.kr/notice/414#windowopen" style="color:blue;">☞ 세차리워드 안내 자세히 보기 (PC)</a></dd>'
	+'<dt name="#faq2"><span>Q</span> 이용 요금은 어떻게 지불해야 하나요?</dt>'
	+'<dd style=""><span>A</span> 쏘카 서비스 가입 시 등록한 결제카드를 통해 이용금액이 지불됩니다. 예약하신 시간 수 분 전에 자동으로 결제되며 사용 반납 후 km당 주행요금이 결제 됩니다.</dd>'
	+'<dt name="#faq3"><span>Q</span> 신용카드만 가능한가요? 체크카드는 등록이 안되나요?</dt>'
	+'<dd style=""><span>A</span> 신용카드, 체크카드 둘다 등록 가능합니다. 단, 체크카드 등록 후 이용금액이 충분하지 않아 결제가 정상적으로 되지 않을 시에는 차량 이용이 제한됩니다.</dd>'
	+'<dt name="#faq4"><span>Q</span> 쏘카를 반납할 때 연료를 다시 채워야 하나요?</dt>'
	+'<dd style=""><span>A</span> 다음 이용자를 위해서 쏘카 반납 시 잔여연료가 절반이상 남아있는지 반드시 확인해 주세요. 만약 잔여연료 부족으로 다음 이용에 문제가 발생한 경우 페널티금액이 부과될 수 있습니다.</dd>'
	+'<dt name="#faq5"><span>Q</span> 주유는 어떻게 해야 하나요? 비용은 누가 내나요?</dt>'
	+'<dd style=""><span>A</span> 이용 중 주유가 필요하면 반드시 차량 내부에 비치된 주유카드를 이용해 결제해 주시기 바랍니다. 다음 사용자를 위해 연료 잔량을 체크하시고 미리미리 주유해 주시기 바랍니다. 주유하신 금액은 사용 종료 후 총 주행거리 기준으로 계산되어 등록하신 결제카드로 후불 결제됩니다. 주행거리당 요금은 유가변동에 따라 주기적으로 변동될 수 있습니다.<br><br>'
	+'<br><br>'
	+'※ 쏘카 차량 주유시 개인카드 및 현금으로 결제하시면 환불되지 않습니다.</dd>'
	+'<dt name="#faq6"><span>Q</span> 결제카드 등록은 꼭 해야 하나요?</dt>'
	+'<dd style=""><span>A</span> 쏘카 서비스 가입 및 이용을 위해서는 반드시 결제카드 등록을 해야 합니다. 카셰어링 서비스에서 카드 등록은 회원의 차량 예약 변경 및 기타 페널티 발생을 대비한 최소한의 조건입니다. 결제 금액 및 날짜를 사전에 공지해 드리고 있으니 카드를 등록하시고 편리하게 이용하기 바랍니다.</dd>'
	+'<dt name="#faq7"><span>Q</span> 예약 연장이 가능한가요?</dt>'
	+'<dd style=""><span>A</span> 회원님이 사용 중인 차량이 다른 회원이 대기 중인 차량이 아닐 경우에는 차량 연장이 가능합니다. 예약연장은 홈페이지와 스마트폰 앱, 콜센터 상담원을 통해 가능합니다. 다만, 추가 연장 예약을 하지 않거나 콜센터 조치에 의해 사용연장이 되지 않은 상태에서 임의적으로 계속 사용할 경우, 시간당 페널티가 과금될 수 있습니다.</dd>'
	+'<dt name="#faq8"><span>Q</span> 내가 예약한 동안 차량은 다른 사람이 운전해도 되나요?</dt>'
	+'<dd style=""><span>A</span> 예약한 회원 본인과 예약 시 지정한 추가 운전자 1인만 쏘카를 운전 할 수 있습니다. 이 외 쏘카와 협의되지 않은 제 3자가 운전하거나 예약자 없이 동승 운전자가 단독운행하여 발생한 사고는 보험 혜택 등을 적용 받을 수 없습니다. <br><br>'
	+'<br><br>'
	+'동승 운전자 추가 지정 방법은 아래 공지사항을 참고해주세요.<br><br>'
	+'<a href="http://www.socar.kr/cs/notice_view/19#windowopen">http://www.socar.kr/cs/notice_view/19</a></dd>'
	+'<dt name="#faq9"><span>Q</span> 차량 이용 중 사고가 나거나 긴급 출동이 필요할 때는 어떻게 해야 하나요?</dt>'
	+'<dd style=""><span>A</span> 차량 이용 중 고장이나 사고 발생 시 고객센터(1661-3315)로 즉시 연락해 신고해야 하며 회사의 안내를 준수해야 합니다. 사고 후 신고하지 않은 경우에는 보험 혜택을 적용받을 수 없으며 미신고 페널티 금액이 징구됩니다.</dd>'
	+'<dt name="#faq10"><span>Q</span> 보험에는 어떤 내용이 포함되어 있나요?</dt>'
	+'<dd style=""><span>A</span> 모든 쏘카는 자동차 종합보험(대인배상, 대물배상, 자기신체사고) 및 선택하신 보험료에 따라 차량손해 면책제도가 모든 차량에 적용됩니다. 대여시 선택하신 보험료에 따라 차량수리비가 면책금 미만인 경우 실비 정산을 하며, 가입된 면책금 이상인 경우 면책금만 지불하시면 됩니다. 단, 휴차료는 실제 수리일수에 따라 별도로 계산됩니다.<br><br>'
	+'<br><br>'
	+'- 휴차보상료 : 수리기간이 길어져도 최대 5일까지 휴차일 산정 (휴차료 산정 기준 : 해당 차량 1일 기준요금의 50%) / 폐차 발생시 별도의 휴차일 산정 기준을 따릅니다.<br><br>'
	+'<br><br>'
	+'보험에 가입되어 있어도 사고 발생 즉시 신고하지 않았거나 음주운전 사고로 인한 손해, 예약자 이외의 운전자가 일으킨 사고, 1종보통 이상의 면허 소지자 외에 승합차량운전 등 쏘카대여약관에 의거한 손해면책 사항에 해당하는 경우 자기차량 손해면책제도에서 제외되며, 법적 고발 및 이용 불가 조치가 행해질 수 있습니다.<br><br>'
	+'<br><br>'
	+'만약 상해나 재물상의 손실이 본사의 배상 한도를 초과했을 경우에는 회원이 이 초과분에 대하여 지급할 책임이 있으며 관련 보험사나 상대측 보험사와 컨택하여 처리 할 수 있습니다. 회원의 허가되지 않은 사용에 대한 사건 및 사고는 보험으로 배상되지 않습니다. 비회원의 운전은 금지되어 있으며 이로 인한 사고의 피해도 보험적용이 되지 않으며 기존 회원의 회원자격 상실의 사유가 됩니다. 차량 이용 및 보험에 관한 사항은 쏘카 자동차대여약관에 따릅니다. 쏘카 회원이용약관 및 자동차대여약관은 차량 예약 전에 꼭 숙지해주세요.</dd>'
	+'</dl>'
	+'</fieldset>'
	+'</form>'
	+'<div id="pagination" class="pagination" style="margin-top: 15px;">'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>';
	
var customer_faq_1_form =
	'<div id= "customer" class="faq">'
	+'<div id="container" class="box">'
	+'<div id="content">'
	+'<h2><img src="'+app.img()+'/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
	+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
	+'<div class="faq_lnb">'
	+'<ul class="lnb faq_lnb">'
	+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
	+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
	+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
	+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
	+'</ul>'
	+'<div class="section1">'
	+'<h3><img src="http://socdnw.speedgabia.com/template/asset/images/customer/h3_faq.gif" alt="자주묻는 질문"></h3>'
	+'<div class="search-box">'
	+'<form class="faq_form" name="search" method="post" action="">'
	+'<fieldset>'
	+'<select>'
	+'<option selected="selected">전체</option>'
	+'</select>'
	+'<input type="text" class="input">'
	+'<input id="btn_search" type="image" class="submit" src="http://socdnw.speedgabia.com/template/asset/images/customer/btn_faq_search.gif" alt="검색">'
	+'</fieldset>'
	+'</form>'
	+'</div>'
	+'<form class="faq_form" name="faq" method="post" action="">'
	+'<fieldset>'
	+'<div class="tab">'
	+'<ul>'
	+'<li><a href="#" class="btn_category tab1 0">자주묻는 질문</a></li>'
	+'<li class="on"><a href="${context}/admin/faq_1" class="btn_category tab2 1">예약/결제문의</a></li>'
	+'<li><a href="${context}/admin/faq_2" class="btn_category tab3 2">가입문의</a></li>'
	+'<li><a href="${context}/admin/faq_3" class="btn_category tab4 3">차량이용/사고</a></li>'
	+'<li><a href="${context}/admin/faq_4" class="btn_category tab5 4">프로모션/쿠폰</a></li>'
	+'<li><a href="${context}/admin/faq_5" class="btn_category tab6 5">법인/단체</a></li>'
	+'<li><a href="${context}/admin/faq_6" class="btn_category tab7 6">탈퇴</a></li>'
	+'<li><a href="${context}/admin/faq_7" class="btn_category tab8 7">기타</a></li>'
	+'</ul>'
	+'</div>'
	 +'<p class="count">총게시물 <strong>35</strong>개</p>'
	+'<dl class="faq-list">'
	+'<dt name="#faq1" class="active"><span>Q</span> 딱 10분을 남겨두고 반납했어요. 바로반납 혜택이 제공이 되나요?</dt>'
	+'<dd style="display: block;"><span>A</span> 바로반납 혜택은 대여시간 30분 초과, 대여 종료시간 10분 이전 건에 대하여 적용됩니다.<br><br>'
	+'바로반납 크레딧에 대한 자세한 내용은 아래 공지사항을 참고해주세요.<br><br>'
	+'<a href="http://www.socar.kr/notice/586#windowopen" style="color:blue;">☞ 바로반납 크레딧 안내 자세히 보기 (PC)</a></dd>'
	+'<dt name="#faq2"><span>Q</span> 바로반납 혜택이 아직 들어오지 않았어요!</dt>'
	+'<dd><span>A</span> 바로반납 혜택은 지급되기까지 약 1시간정도 소요될 수 있습니다.<br><br>'
	+'단, 미결제 요금이 존재하는 경우 크레딧 제공이 보류될 수 있습니다.<br><br>'
	+'정상적으로 결제가 이루어졌으나 지급되지 않았다면 고객센터 1:1문의 혹은 쏘카톡으로 문의주세요.<br><br>'
	+'바로반납 크레딧에 대한 자세한 내용은 아래 공지사항을 참고해주세요.<br><br>'
	+'<a href="http://www.socar.kr/notice/586#windowopen" style="color:blue;">☞ 바로반납 크레딧 안내 자세히 보기 (PC)</a></dd>'
	+'<dt name="#faq3"><span>Q</span> 편도나 D2D 서비스의 경우에도 바로반납 혜택이 적용되나요?</dt>'
	+'<dd><span>A</span> 편도나 D2D와 같은 부가서비스 요금은 바로반납 혜택에 포함이 되지않습니다.<br><br>'
	+'다만, 해당 예약건의 대여요금은 위와 동일하게 바로반납 혜택 대상에 포함됩니다.<br><br>'
	+'바로반납 크레딧에 대한 자세한 내용은 아래 공지사항을 참고해주세요.<br><br>'
	+'<a href="http://www.socar.kr/notice/586#windowopen" style="color:blue;">☞ 바로반납 크레딧 안내 자세히 보기 (PC)</a></dd>'
	+'<dt name="#faq4"><span>Q</span> 잔액부족으로 결제가 이루어지지 않은 경우에도 바로반납을 할 경우 혜택을 받을 수 있나요?</dt>'
	+'<dd><span>A</span> 바로반납 시, 미결제요금이 있다면 바로반납 혜택 지급이 보류됩니다. <br><br>'
	+'단, 14일 이내에 미결제요금을 결제 완료되면 바로반납 혜택이 지급됩니다.<br><br>'
	+'바로반납 크레딧에 대한 자세한 내용은 아래 공지사항을 참고해주세요.<br><br>'
	+'<a href="http://www.socar.kr/notice/586#windowopen" style="color:blue;">☞ 바로반납 크레딧 안내 자세히 보기 (PC)</a></dd>'
	+'<dt name="#faq5"><span>Q</span> 바로반납으로 받은 혜택의 유효기간은 언제까지 인가요?</dt>'
	+'<dd><span>A</span> 바로반납 크레딧의 유효기간은 지급된 시점으로부터 180일이며, 쿠폰의 경우 30일입니다.<br><br>'
	+'바로반납 크레딧에 대한 자세한 내용은 아래 공지사항을 참고해주세요.<br><br>'
	+'<a href="http://www.socar.kr/notice/586#windowopen" style="color:blue;">☞ 바로반납 크레딧 안내 자세히 보기 (PC)</a></dd>'
	+'<dt name="#faq6"><span>Q</span> 예약 앞당기기, 반납연장을 했어요. 이때 발생한 시간도 바로반납 혜택에 포함되나요?</dt>'
	+'<dd><span>A</span> 네, 포함됩니다. 예약 앞당기기나 반납연장을 통해 실제 대여시간이 늘어났다면, 변경된 대여시작시간과 반납시간을 기준으로 혜택이 지급됩니다.<br><br>'
	+'바로반납 크레딧에 대한 자세한 내용은 아래 공지사항을 참고해주세요.<br><br>'
	+'<a href="http://www.socar.kr/notice/586#windowopen" style="color:blue;">☞ 바로반납 크레딧 안내 자세히 보기 (PC)</a></dd>'
	+'<dt name="#faq7"><span>Q</span> 바로반납 혜택을 제공하는 기준은 어떻게 되나요?</dt>'
	+'<dd><span>A</span> 반납 시 잔여대여시간의 50%가 크레딧으로 지급됩니다. <br><br>'
	+'단, 받을 크레딧이 0원이면 1,000원 쿠폰이 지급됩니다.<br><br>'
	+'쏘친님의 반납시점에 따라 혜택이 달라질 수 있으니, 반납 후 직접 확인해주세요!<br><br>'
	+'바로반납 크레딧에 대한 자세한 내용은 아래 공지사항을 참고해주세요.<br><br>'
	+'<a href="http://www.socar.kr/notice/586#windowopen" style="color:blue;">☞ 바로반납 크레딧 안내 자세히 보기 (PC)</a></dd>'
	+'<dt name="#faq8"><span>Q</span> 쿠폰이나 크레딧으로 쏘카를 이용한 경우에도 바로반납 혜택을 받을 수 있나요?</dt>'
	+'<dd><span>A</span> 쏘카 대여시 결제된 대여요금 + 보험료 (카드, 크레딧결제)가 바로반납 혜택의 대상이 됩니다.<br><br>'
	+'단, 쿠폰 및 할인금액은 혜택에 적용이 되지 않습니다.<br><br>'
	+'예) 2시간 대여 시 2시간 무료쿠폰(대여요금 0원) + 보험료(1,000크레딧)인 경우,<br><br>'
	+'쏘친이 실제로 결제한 금액은 1,000원으로, 500크레딧이 적립됩니다.<br><br>'
	+'<br><br>'
	+'바로반납 크레딧에 대한 자세한 내용은 아래 공지사항을 참고해주세요.<br><br>'
	+'<a href="http://www.socar.kr/notice/586#windowopen" style="color:blue;">☞ 바로반납 크레딧 안내 자세히 보기 (PC)</a></dd>'
	+'<dt name="#faq9"><span>Q</span> 24시간 대여하고 10시간 사용 후 바로반납 시 14시간 바로반납 혜택을 받나요?</dt>'
	+'<dd><span>A</span> 아니요. <br><br>'
	+'24시간 대여요금은 장시간 예약고객을 대상으로 부담을 덜어드리기 위하여, 10시간 이상 대여 시 최대 24시간(일일대여시)까지는 무료로 제공해드리는 시간입니다.<br><br>'
	+'따라서, 10시간 이상 이용 후 반납하더라도 바로반납 혜택에 포함되지 않습니다.<br><br>'
	+'바로반납 크레딧에 대한 자세한 내용은 아래 공지사항을 참고해주세요.<br><br>'
	+'<a href="http://www.socar.kr/notice/586#windowopen" style="color:blue;">☞ 바로반납 크레딧 안내 자세히 보기 (PC)</a></dd>'
	+'<dt name="#faq10"><span>Q</span> D2D 차량 중 일부차종(그랜저HG, SM5, 카니발(11인승) 등)을 예약할 수 없어요.</dt>'
	+'<dd><span>A</span> D2D 이용가능 차종 중 <br><br>'
	+'그랜저HG, LF소나타, SM5, 스타렉스(일부차량) 차종은 SK네트웍스에서 위탁받은 차량으로<br><br>'
	+'만 26세 이상 쏘친에 한하여 예약이 가능합니다.<br><br>'
	+'<br><br>'
	+'스타렉스와 카니발 11인승 차종은 1종보통 면허 소지자에 한하여 예약이 가능합니다.</dd>'
	+'</dl>'
	+'</fieldset>'
	+'</form>'
	+'<div id="pagination" class="faq_pagination" style="margin-top: 15px; position: absolute; left: 371.5px;">'
	+'<span class="current prev">&lt;</span>'
	+'<span class="current">1</span>'
	+'<a href="">2</a>'
	+'<a href="">3</a>'
	+'<a href="">4</a>'
	+'<a href="" class="next">&gt;</a>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>';

var customer_faq_2_form =
	'<div id= "customer" class="faq">'
	+'<div id="container" class="box">'
	+'<div id="content">'
	+'<h2><img src="'+app.img()+'/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
	+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
	+'<div class="faq_lnb">'
	+'<ul class="lnb faq_lnb">'
	+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
	+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
	+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
	+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
	+'</ul>'
	+'<div class="section1">'
	+'<h3><img src="http://socdnw.speedgabia.com/template/asset/images/customer/h3_faq.gif" alt="자주묻는 질문"></h3>'
	+'<div class="search-box">'
	+'<form class="faq_form" name="search" method="post" action="">'
	+'<fieldset>'
	+'<select>'
	+'<option selected="selected">전체</option>'
	+'</select>'
	+'<input type="text" class="input">'
	+'<input id="btn_search" type="image" class="submit" src="http://socdnw.speedgabia.com/template/asset/images/customer/btn_faq_search.gif" alt="검색">'
	+'</fieldset>'
	+'</form>'
	+'</div>'
	+'<form class="faq_form" name="faq" method="post" action="">'
	+'<fieldset>'
	+'<div class="tab">'
	+'<ul>'
	+'<li ><a href="#" class="btn_category tab1 0">자주묻는 질문</a></li>'
	+'<li><a href="${context}/admin/faq_1" class="btn_category tab2 1">예약/결제문의</a></li>'
	+'<li class="on"><a href="${context}/admin/faq_2" class="btn_category tab3 2">가입문의</a></li>'
	+'<li><a href="${context}/admin/faq_3" class="btn_category tab4 3">차량이용/사고</a></li>'
	+'<li><a href="${context}/admin/faq_4" class="btn_category tab5 4">프로모션/쿠폰</a></li>'
	+'<li><a href="${context}/admin/faq_5" class="btn_category tab6 5">법인/단체</a></li>'
	+'<li><a href="${context}/admin/faq_6" class="btn_category tab7 6">탈퇴</a></li>'
	+'<li><a href="${context}/admin/faq_7" class="btn_category tab8 7">기타</a></li>'
	+'</ul>'
	+'</div>'
	 +'<p class="count">총게시물 <strong>11</strong>개</p>'
	+'<dl class="faq-list">'
	+'<dt name="#faq1" class="active"><span>Q</span> 회원카드는 어떻게 구매할 수 있나요?</dt>'
	+'<dd style="display: block;"><span>A</span> 회원카드는 가입완료 후&nbsp;모바일앱 마이페이지 &gt; 내 정보 &gt; 차량제어수단 &gt;&nbsp;추가 카드키 &gt; 회원카드 신청 을 통해 구매하실 수 있습니다. <br><br>'
	+'<br><br>'
	+'※ 회원카드 수령과 관계없이 가입승인 후 모바일앱/웹 스마트키로 쏘카를 이용하실 수 있습니다.</dd>'
	+'<dt name="#faq2"><span>Q</span> 회원카드는 언제, 어떻게 등록할 수 있나요?</dt>'
	+'<dd><span>A</span> 구매한 회원카드를 수령하신 이후, 모바일앱 마이페이지 &gt; 내 정보 &gt; 차량제어수단 &gt; 카드수정 에서 회원카드번호 7자리를 등록해주세요.<br><br>'
	+'<br><br>'
	+'※ 회원카드 수령과 관계없이 가입승인 후 모바일앱/웹 스마트키로 쏘카를 이용하실 수 있습니다.</dd>'
	+'<dt name="#faq3"><span>Q</span> 회원카드를 직접 방문수령하여 받을 수 있나요?</dt>'
	+'<dd><span>A</span> 가능합니다! 사용 일정이 급하신 분들의 경우 스마트폰 앱으로 바로 이용 가능합니다. 회원카드 수령을 바로 원하는 경우 고객센터(1661-3315)로 연락 주시고, 쏘카 서울/제주 사무실로 오셔서 방문 수령하실 수 있습니다.</dd>'
	+'<dt name="#faq4"><span>Q</span> 회원이 되려면 얼마나 걸리나요?</dt>'
	+'<dd><span>A</span> 쏘카 홈페이지에서 회원 가입하시면, 회원님의 개인정보, 운전면허 정보, 신용카드 정보  등을 확인하는 과정을 거칩니다. 정보에 문제가 없는 경우 회원가입 1일 이내 쏘카 회원으로 승인됩니다.<br><br>'
	+'</dd>'
	+'<dt name="#faq5"><span>Q</span> 연회비 제도가 있나요?</dt>'
	+'<dd><span>A</span> 쏘카에서는 별도 연회비가 없이 모든 서비스를 이용하실 수 있습니다.<br><br>'
	+'<br><br>'
	+'※ 쏘카 SO회원에 한해 적용되던 연회비가 2014년 1월 9일 부로 무료화되었습니다. 대여요금 최대 70% 할인 등, SO회원 혜택은 그대로 유지됩니다. 회원제에 대해 궁금하신 사항은 고객센터(1661-3315)로 문의 부탁드립니다.</dd>'
	+'<dt name="#faq6"><span>Q</span> 회원카드 배송은 언제 되나요?</dt>'
	+'<dd><span>A</span> 회원카드 배송은 신청일로부터 주말/공휴일 제외 5~7일 정도 소요되며, 회원정보에 등록된 주소로 배송됩니다. 주소를 잘못 기입하여 반송되는 경우 추가 비용이 청구될 수 있으니, 반드시 우편물 수령이 가능한 주소를 입력해 주세요. <br><br>'
	+'※ 회원카드 신청 후 한달 이상 경과하여도 카드를 받지 못하셨다면, 고객센터(1661-3315)로 별도 문의해 주세요. <br><br>'
	+'※ 회원카드 수령과 관계없이 가입승인 후 모바일 앱/웹 스마트키로 쏘카를 이용하실 수 있습니다.</dd>'
	+'<dt name="#faq7"><span>Q</span> 가입절차가 어떻게 되나요?</dt>'
	+'<dd><span>A</span> 회원가입은 쏘카 홈페이지 및 모바일웹/앱에서 가능합니다. 회원가입 시 실명인증 및 연락처, 이메일, 주소 등의 개인정보와 결제카드정보 및 운전면허 정보를 모두 입력해 주셔야 합니다. 회원가입을 완료하시면 입력하신 정보가 사실과 맞는지 검토하는 과정을 거쳐, 심사가 정상적으로 완료된 후부터 쏘카 예약 및 이용이 가능합니다.</dd>'
	+'<dt name="#faq8"><span>Q</span> 가입 후 바로 차를 이용할 수 있나요?</dt>'
	+'<dd><span>A</span> 쏘카 회원 가입을 완료하시면 입력하신 정보가 사실과 맞는지 소정의 심사과정을 진행하게 됩니다. 심사가 정상적으로 완료 된 후 쏘카 이용이 가능하며, 쏘카 스마트폰 앱을 다운 받으시면 회원카드 없이 예약 및 사용이 가능합니다. 회원카드는 마이페이지 &gt; 내정보에서 신청하시면 우편으로 배송되며(비용 1,500원), 주말 및 공휴일 제외 5~7일 정도 소요됩니다.</dd>'
	+'<dt name="#faq9"><span>Q</span> 결제카드 등록은 꼭 해야 하나요?</dt>'
	+'<dd><span>A</span> 쏘카 서비스 가입 및 이용을 위해서는 반드시 결제카드 등록을 해야 합니다. 카셰어링 서비스에서 카드 등록은 회원의 차량 예약 변경 및 기타 페널티 발생을 대비한 최소한의 조건입니다. 결제 금액 및 날짜를 사전에 공지해 드리고 있으니 카드를 등록하시고 편리하게 이용하기 바랍니다.<br><br>'
	+'</dd>'
	+'<dt name="#faq10"><span>Q</span> 스마트폰으로 차량 예약을 어떻게 하나요?</dt>'
	+'<dd><span>A</span> 홈페이지를 통해 회원가입 후 간편하게 스마트폰 앱을 이용하여 쏘카 이용이 가능합니다. 회원가입 후 승인이 완료 되면 스마트폰 앱 로그인이 가능하며, 원하는 차종 및 시간, 지역 선택 후 예약이 가능합니다.<br><br>'
	+'</dd>'
	+'</dl>'
	+'</fieldset>'
	+'</form>'
	+'<div id="pagination" class="faq_pagination" style="margin-top: 15px; position: absolute; left: 371.5px;"><span class="current prev">&lt;</span><span class="current">1</span><a href="">2</a><a href="" class="next">&gt;</a></div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>';

var customer_faq_3_form =
	'<div id= "customer" class="faq">'
	+'<div id="container" class="box">'
	+'<div id="content">'
	+'<h2><img src="'+app.img()+'/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
	+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
	+'<div class="faq_lnb">'
	+'<ul class="lnb faq_lnb">'
	+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
	+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
	+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
	+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
	+'</ul>'
	+'<div class="section1">'
	+'<h3><img src="http://socdnw.speedgabia.com/template/asset/images/customer/h3_faq.gif" alt="자주묻는 질문"></h3>'
	+'<div class="search-box">'
	+'<form class="faq_form" name="search" method="post" action="">'
	+'<fieldset>'
	+'<select>'
	+'<option selected="selected">전체</option>'
	+'</select>'
	+'<input type="text" class="input">'
	+'<input id="btn_search" type="image" class="submit" src="http://socdnw.speedgabia.com/template/asset/images/customer/btn_faq_search.gif" alt="검색">'
	+'</fieldset>'
	+'</form>'
	+'</div>'
	+'<form class="faq_form" name="faq" method="post" action="">'
	+'<fieldset>'
	+'<div class="tab">'
	+'<ul>'
	+'<li ><a href="#" class="btn_category tab1 0">자주묻는 질문</a></li>'
	+'<li><a href="${context}/admin/faq_1" class="btn_category tab2 1">예약/결제문의</a></li>'
	+'<li><a href="${context}/admin/faq_2" class="btn_category tab3 2">가입문의</a></li>'
	+'<li class="on"><a href="${context}/admin/faq_3" class="btn_category tab4 3">차량이용/사고</a></li>'
	+'<li><a href="${context}/admin/faq_4" class="btn_category tab5 4">프로모션/쿠폰</a></li>'
	+'<li><a href="${context}/admin/faq_5" class="btn_category tab6 5">법인/단체</a></li>'
	+'<li><a href="${context}/admin/faq_6" class="btn_category tab7 6">탈퇴</a></li>'
	+'<li><a href="${context}/admin/faq_7" class="btn_category tab8 7">기타</a></li>'
	+'</ul>'
	+'</div>'
	 +'<p class="count">총게시물 <strong>38</strong>개</p>'
	+'<dl class="faq-list">'
	+'<dt name="#faq1" class="active"><span>Q</span> 반납 체크 사항을 모두 처리하였는데도, "바로 반납"이 되지 않아요.</dt>'
	+'<dd style="display: block;"><span>A</span> 고객센터(1661-3315)로 연락 주시면 확인 후에 도와드릴게요. 문제 발생 시에는 바로 연락 주세요.<br><br>'
	+'바로반납 크레딧에 대한 자세한 내용은 아래 공지사항을 참고해주세요.<br><br>'
	+'<a href="http://www.socar.kr/notice/586#windowopen" style="color:blue;">☞ 바로반납 크레딧 안내 자세히 보기 (PC)</a></dd>'
	+'<dt name="#faq2"><span>Q</span> 제주도 쏘카 셔틀버스 이용요금은 무료인가요?</dt>'
	+'<dd><span>A</span> 네, 쏘친님들이 쏘카 스테이션으로 편하고 안전하게 이동하실 수 있도록 쏘카에서 제공하는 무료 서비스입니다. <br><br>'
	+'운영 시간은 오전 8시부터 오후 8시까지 12시간이며, 30분 간격으로 운행합니다.</dd>'
	+'<dt name="#faq3"><span>Q</span> 제주공항 쏘카 셔틀버스 운영시간 외에는 어떻게 제주 쏘카스테이션에 찾아가나요?</dt>'
	+'<dd><span>A</span> 제주공항에서 대중교통을 이용하여 제주 쏘카 스테이션으로 이동이 가능합니다.<br><br>'
	　+'버스: (신제주방면) 37번, 38번, 200번, 500번, 1002번(심야) 1003번(심야), 1009번(주말 심야) <br><br>'
	　　　　+'그레이스호텔 정류장 하차 (약 20분) -&gt; 제주공항 방면 도보 이동 (약 5분)<br><br>'
	　+'택시: 연동 삼성전자 서비스센터 옆 라마다 앙코르 호텔 주차장 (약 7분소요)<br><br>'
	+'</dd>'
	+'<dt name="#faq4"><span>Q</span> 제주공항에서 쏘카 셔틀버스를 어떻게 알아볼 수 있나요?</dt>'
	+'<dd><span>A</span> 파란 셔틀버스에 쏘카 디자인이 되어 있는 버스가 쏘카 셔틀버스입니다. 제주공항 3층 2번게이트 쪽 버스 승하차장에서 대기하고 있는 파란색 쏘카 버스를 찾아주세요.</dd>'
	+'<dt name="#faq5"><span>Q</span> D2D 이용가능지역은 어디인가요?</dt>'
	+'<dd><span>A</span> <div>2016년 9월, 서울 전지역에 서비스를 제공 중 입니다. 점진적으로 서비스 지역은 확대될 예정입니다.</div></dd>'
	+'<dt name="#faq6"><span>Q</span> D2D 이용 후 바로 반납이 되질 않습니다.</dt>'
	+'<dd><span>A</span> <div>일단, 차량시동 OFF, 문잠금 상태인지 확인 및 차량 위치가 처음 대여 요청한 곳 인근 지역인지 다시금 확인해 주세요.</div><div>D2D 예약의 경우 반납한 곳의 차량 위치에 대한 정보 및 사진을 기입을 해야만 바로반납이 됩니다.</div><div>(반납시 입력한 위치 정보 및 사진은 차량을 다시 복귀하기 위해 찾는 정보로 활용 됩니다)</div><div>간혹, 지하 주차장인 경우나 인근 빌딩 밀집 지역인 경우 위치 정보 확인이 어려울 수 있습니다.</div><div>반납이 원할하지 않는 경우 1661-4665번(D2D 서비스전용)으로 문의바랍니다.</div><div>※ D2D 예약이 아닌 일반 예약은 고객센터(1661-3315)로 문의바랍니다.</div></dd>'
	+'<dt name="#faq7"><span>Q</span> D2D 이용을 마친 후 차량 반납은 어떻게 하나요?</dt>'
	+'<dd><span>A</span> <div>D2D 이용 후 차량 반납은 맨처음 예약시 배차를 요청하셨던 곳에 주차 해주세요.</div><div>그 다음 APP에서 바로반납을 처리 진행해 주시면 됩니다.</div><div>처음 출발한 곳에 주차가 원할하지 못한 경우 인근지역에 주차후 바로반납해주세요.</div>반납이 원할하지 않는 경우엔 1661-4665번(D2D 서비스전용)으로 문의바랍니다<div>&nbsp;※ D2D 예약이 아닌 일반 예약은 고객센터(1661-3315)로 문의바랍니다.</div></dd>'
	+'<dt name="#faq8"><span>Q</span> D2D 예약을 취소하고 싶어요.</dt>'
	+'<dd><span>A</span> <div>D2D 예약 취소는 APP, 홈페이지 예약내역 및 고객센터를 통해 취소 가능하며, 예약한지 30분 이후 또는 이용 3시간 이내 취소하는 경우 취소수수료(대여요금의 10%)가 발생됩니다.</div></dd>'
	+'<dt name="#faq9"><span>Q</span> D2D 차량 배차 시간을 앞당기고 싶어요.</dt>'
	+'<dd><span>A</span> <div>* 배차시간은 최대 2시간이 소요됩니다.</div><div>ㄴ 차량 이용 시작 시간까지 2시간 이상 남았다면, 예약 앞당기기가 가능합니다.</div><div>ㄴ 예시. 현재시간 9월1일 오전 10시, 9월1일 낮 1시 부터 이용하는 예약은 &nbsp;9월1일 낮 12시까지만 예약 앞당기기 가능</div><div><br></div><div>* 차량 이용 시작까지 2시간 보다 덜남은 경우 예약 앞당기기가 어렵습니다.</div><div>&nbsp; ㄴ 차량 배차 중임에 따른 예약 앞당기기 불가</div><div>&nbsp; ㄴ 단, 차량이 배차된 이후에는 예약 앞당기기가 가능합니다.</div></dd>'
	+'<dt name="#faq10"><span>Q</span> D2D 차량을 지금 바로 이용하고 싶어요.</dt>'
	+'<dd><span>A</span> <div>차량을 고객이 원하는 지역까지 차량을 배차하는데 있어 최대 2시간이 소요됩니다.&nbsp;</div><div>차량 이용을 원하는 시간의 최소 2시간 전에는 예약을 진행해 주세요.</div></dd>'
	+'</dl>'
	+'</fieldset>'
	+'</form>'
	+'<div id="pagination" class="faq_pagination" style="margin-top: 15px; position: absolute; left: 371.5px;"><span class="current prev">&lt;</span><span class="current">1</span><a href="">2</a><a href="">3</a><a href="">4</a><a href="" class="next">&gt;</a></div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>';

var customer_faq_4_form =
	'<div id= "customer" class="faq">'
	+'<div id="container" class="box">'
	+'<div id="content">'
	+'<h2><img src="'+app.img()+'/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
	+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
	+'<div class="faq_lnb">'
	+'<ul class="lnb faq_lnb">'
	+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
	+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
	+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
	+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
	+'</ul>'
	+'<div class="section1">'
	+'<h3><img src="http://socdnw.speedgabia.com/template/asset/images/customer/h3_faq.gif" alt="자주묻는 질문"></h3>'
	+'<div class="search-box">'
	+'<form class="faq_form" name="search" method="post" action="">'
	+'<fieldset>'
	+'<select>'
	+'<option selected="selected">전체</option>'
	+'</select>'
	+'<input type="text" class="input">'
	+'<input id="btn_search" type="image" class="submit" src="http://socdnw.speedgabia.com/template/asset/images/customer/btn_faq_search.gif" alt="검색">'
	+'</fieldset>'
	+'</form>'
	+'</div>'
	+'<form class="faq_form" name="faq" method="post" action="">'
	+'<fieldset>'
	+'<div class="tab">'
	+'<ul>'
	+'<li><a href="#" class="btn_category tab1 0">자주묻는 질문</a></li>'
	+'<li><a href="${context}/admin/faq_1" class="btn_category tab2 1">예약/결제문의</a></li>'
	+'<li><a href="${context}/admin/faq_2" class="btn_category tab3 2">가입문의</a></li>'
	+'<li><a href="${context}/admin/faq_3" class="btn_category tab4 3">차량이용/사고</a></li>'
	+'<li class="on"><a href="${context}/admin/faq_4" class="btn_category tab5 4">프로모션/쿠폰</a></li>'
	+'<li><a href="${context}/admin/faq_5" class="btn_category tab6 5">법인/단체</a></li>'
	+'<li><a href="${context}/admin/faq_6" class="btn_category tab7 6">탈퇴</a></li>'
	+'<li><a href="${context}/admin/faq_7" class="btn_category tab8 7">기타</a></li>'
	+'</ul>'
	+'</div>'
	+'<p class="count">총게시물 <strong>10</strong>개</p>'
	+'<dl class="faq-list">'
	+'<dt name="#faq1" class="active"><span>Q</span> 쏘카존의 다양한 마커들은 어떤 의미인가요?</dt>'
	+'<dd style="display: block;"><span>A</span> 쏘카 예약 페이지의 각 마커들은&nbsp;<div><img src="http://m.socar.kr/template/asset/images/pin1/mobilepin1.png?20140116" width="34" height="35">신규존&nbsp;</div><div><img src="http://m.socar.kr/template/asset/images/pin2/mobilepin1.png?20140116" width="34" height="35">할인존&nbsp;</div><div><img src="http://m.socar.kr/template/asset/images/pin5/mobilepin1.png?20140116" width="34" height="35">핫딜존&nbsp;</div><div><img src="http://m.socar.kr/template/asset/images/pin7/mobilepin1.png?20140116" width="34" height="35">쏘떼차량이 있는 존 입니다.&nbsp;</div><div><br></div><div>* 신규존은&nbsp;쿠폰북에서 신규존 할인 쿠폰을 다운받아 적용하실 수 있습니다.&nbsp;</div><div>* 핫딜존은 쏘카의 게릴라 할인존으로 쿠폰북에서 다운받으신 핫딜전용 할인쿠폰을 적용하실 수 있는 쏘카존입니다. 핫딜존은 주중 월~수요일 오후 3시 오픈됩니다.</div></dd>'
	+'<dt name="#faq2"><span>Q</span> 쿠폰적용을 하면 주행요금을 지불하지 않아도 되나요?</dt>'
	+'<dd><span>A</span> 쿠폰은 대여요금에만 적용 가능하며 보험료, 주행요금 및 추가 연장요금 등 최초 대여요금 외 비용은 예약 시 선택한 결제카드로 결제가 됩니다.</dd>'
	+'<dt name="#faq3"><span>Q</span> 마이페이지에서는 보유쿠폰이 확인되나, 예약 시 적용이 되지 않습니다.</dt>'
	+'<dd><span>A</span> 쿠폰은 각각 사용조건(주중/주말, 쏘카존 제한, 사용기간 제한 여부 등)이 있기 때문에, 예약을 원하시는 일정에 사용 가능한 쿠폰인지, 사용조건을 다시 한번 확인해주세요!</dd>'
	+'<dt name="#faq4"><span>Q</span> 이미 등록된 쿠폰을 다른 사람에게 양도할 수 있나요?</dt>'
	+'<dd><span>A</span> 이미 회원님 계정에 등록이 된 쿠폰은 양도가 불가합니다.</dd>'
	+'<dt name="#faq5"><span>Q</span> 쿠폰을 적용하여 예약하였습니다. 예약을 취소하면 쿠폰도 함께 삭제되나요?</dt>'
	+'<dd><span>A</span> 쿠폰의 유효기간 내, 쿠폰이 적용된 예약을 취소하시면 쿠폰은 다시 재발급이 된답니다.</dd>'
	+'<dt name="#faq6"><span>Q</span> 예약 후 연장을 하려 합니다. 연장시간에 쿠폰적용이 가능한가요?</dt>'
	+'<dd><span>A</span> 쿠폰은 최초 예약 시 차량 대여요금에만 적용이 가능합니다. 연장하시는 경우에는 쿠폰적용이 불가능합니다.</dd>'
	+'<dt name="#faq7"><span>Q</span> 5시간 무료이용 쿠폰이 있습니다. 2시간, 3시간으로 나눠서 이용할 수 있나요?</dt>'
	+'<dd><span>A</span> 쿠폰은 분할이용이 불가합니다. 쿠폰을 적용하여 예약하시는 경우, 예약시간이 무료이용시간보다 짧은 경우에도 남은 시간만큼은 환불이 불가능합니다.</dd>'
	+'<dt name="#faq8"><span>Q</span> 2개의 쿠폰이 있습니다. 예약 시 2개의 쿠폰 모두 적용이 가능하나요?</dt>'
	+'<dd><span>A</span> 쿠폰은 한 예약에 1개만 사용 가능합니다.</dd>'
	+'<dt name="#faq9"><span>Q</span> 예약 시 쿠폰은 어떻게 적용하나요?</dt>'
	+'<dd><span>A</span> 예약 시 이용 원하는 시간, 쏘카존을 선택한 후 마지막 예약확인 페이지에서 보유쿠폰을 선택하여 적용할 수 있습니다.<br>쿠폰마다 유효기간이 있기 때문에 사용조건 및 유효기간을 확인하고 적용해주세요.</dd>'
	+'<dt name="#faq10"><span>Q</span> 보유쿠폰 확인 및 쿠폰등록은 어디서 하나요?</dt>'
	+'<dd><span>A</span> 보유쿠폰은 홈페이지나 모바일 앱의 마이페이지의 "내쿠폰" 메뉴에서 확인이 가능합니다. <br>쿠폰번호를 발급 받으신 경우,&nbsp;마이페이지의&nbsp;“내쿠폰"메뉴에서 우측 상단에 위치한 등록 버튼을 클릭, 쿠폰번호를 입력하여 등록해주세요.</dd>'
	+'</dl>'
	+'</fieldset>'
	+'</form>'
	+'<div id="pagination" class="faq_pagination" style="margin-top: 15px;">'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>';

var customer_faq_5_form =
	'<div id= "customer" class="faq">'
	+'<div id="container" class="box">'
	+'<div id="content">'
	+'<h2><img src="'+app.img()+'/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
	+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
	+'<div class="faq_lnb">'
	+'<ul class="lnb faq_lnb">'
	+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
	+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
	+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
	+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
	+'</ul>'
	+'<div class="section1">'
	+'<h3><img src="http://socdnw.speedgabia.com/template/asset/images/customer/h3_faq.gif" alt="자주묻는 질문"></h3>'
	+'<div class="search-box">'
	+'<form class="faq_form" name="search" method="post" action="">'
	+'<fieldset>'
	+'<select>'
	+'<option selected="selected">전체</option>'
	+'</select>'
	+'<input type="text" class="input">'
	+'<input id="btn_search" type="image" class="submit" src="http://socdnw.speedgabia.com/template/asset/images/customer/btn_faq_search.gif" alt="검색">'
	+'</fieldset>'
	+'</form>'
	+'</div>'
	+'<form class="faq_form" name="faq" method="post" action="">'
	+'<fieldset>'
	+'<div class="tab">'
	+'<ul>'
	+'<li><a href="#" class="btn_category tab1 0">자주묻는 질문</a></li>'
	+'<li><a href="${context}/admin/faq_1" class="btn_category tab2 1">예약/결제문의</a></li>'
	+'<li><a href="${context}/admin/faq_2" class="btn_category tab3 2">가입문의</a></li>'
	+'<li><a href="${context}/admin/faq_3" class="btn_category tab4 3">차량이용/사고</a></li>'
	+'<li><a href="${context}/admin/faq_4" class="btn_category tab5 4">프로모션/쿠폰</a></li>'
	+'<li class="on"><a href="${context}/admin/faq_5" class="btn_category tab6 5">법인/단체</a></li>'
	+'<li><a href="${context}/admin/faq_6" class="btn_category tab7 6">탈퇴</a></li>'
	+'<li><a href="${context}/admin/faq_7" class="btn_category tab8 7">기타</a></li>'
	+'</ul>'
	+'</div>'
	+'<p class="count">총게시물 <strong>8</strong>개</p>'
	+'<dl class="faq-list">'
	+'<dt name="#faq1" class="active"><span>Q</span> 법인/단체 가입시 보증금 또는 연회비 등 비용이 드나요?</dt>'
	+'<dd style="display: block;"><span>A</span> 카셰어링은 회원제로 운영되는 자동차 공유 서비스입니다. 시내의 주요 공영주차장 등 곳곳에 주차된 공유 차량을 필요할 때 언제든 예약하고 사용한 만큼의 비용만 결제하시면 됩니다. 따라서 보증금 또는 연회비가 없으며 물론 계약서도 없습니다.</dd>'
	+'<dt name="#faq2"><span>Q</span> 법인/단체 관리자와 법인 구성원의 차이점이 뭔가요?</dt>'
	+'<dd><span>A</span> 법인/단체 회원은 “관리자”와 “구성원”으로 나뉘며, 관리자는 구성원 가입 승인 및 이용내역 조회를 할 수 있습니다. 구성원은 관리자 승인 후 개인회원과 동일한 프로세스로 이용하게 됩니다.</dd>'
	+'<dt name="#faq3"><span>Q</span> 법인/단체 관리자 계정 등록 후 차량 이용 및 예약이 바로 가능한가요?</dt>'
	+'<dd><span>A</span> 법인/단체 관리자 계정은 소속 직원 초대 및 이용 관리를 위한 계정으로, 차량 이용 및 예약을 위해서는 해당 법인/단체 구성원으로 별도의 가입이 가입이 필요합니다.</dd>'
	+'<dt name="#faq4"><span>Q</span> 관리자가 구성원으로 등록할 경우 동일한 아이디로 가입 및 차량 이용 가능한가요?</dt>'
	+'<dd><span>A</span> 관리자 계정은 별도의 관리계정으로, 구성원 계정과 구분하기 위해 별도의 아이디가 필요합니다. 다만 아이디를 제외한 다른 가입자 정보는 동일하게 사용 가능합니다.</dd>'
	+'<dt name="#faq5"><span>Q</span> 대표카드 결제와 개인카드 결제의 차이점이 뭔가요?</dt>'
	+'<dd><span>A</span> 대표결제는 소속 구성원 전체가 동일한 결제카드를 사용해 결제하며 구성원 개인결제는 각 소속 구성원이 직접 등록한 개별 결제카드로 결제합니다.<br><br>'
	+'이때 개별 결제카드는 개인카드와 법인카드 모두 사용 가능하며 1인당 3장까지 등록해두고 쓸 수 있습니다.</dd>'
	+'<dt name="#faq6"><span>Q</span> 개인사업자도 법인 회원으로 가입하여 법인만의 특혜 서비스를 받을 수 있나요?</dt>'
	+'<dd><span>A</span> 네! 쏘카 법인 프로그램은 업무용 차량 이용을 위한 것으로, 개인사업자도 법인 회원으로 가입해 법인 특혜 서비스를 동일하게 받을 수 있습니다.</dd>'
	+'<dt name="#faq7"><span>Q</span> 현재 개인회원으로 이용 중인데 왜 법인 관리자 또는 법인 구성원으로 재가입을 해야 하나요?</dt>'
	+'<dd><span>A</span> 법인 회원으로 이용하면 주중 이용요금 할인 등 더 많은 혜택이 제공됩니다. 업무용으로 이용하실 때는 법인 구성원으로 가입하셔서 더 많은 혜택을 누려보세요.</dd>'
	+'<dt name="#faq8"><span>Q</span> 오토리스 또는 장기렌트와 비교 시 장점이 뭔가요?</dt>'
	+'<dd><span>A</span> <strong> 경제적입니다!</strong><br><br>'
	+'- 선수금, 보증금 등 별도 비용을 지불할 필요가 없습니다.<br><br>'
	+'- 최소 30분부터 10분 단위로, 이용한 시간과 운행한 거리만큼만 요금을 부담할 수 있어 비용절감이 가능합니다.<br><br>'
	+'- 또 차량관리 및 주차관리로 인한 낭비가 없어 경제적이고 효율적입니다.<br><br>'
	+'<br><br>'
	+'<strong> 간단합니다!</strong><br><br>'
	+'방문 및 별도 서류 작성 없이 스마트폰/PC로 가입 후 바로 이용할 수 있습니다. <br><br>'
	+'<br><br>'
	+'<strong> 편리합니다!</strong><br><br>'
	+'365일 24시간 사무실 주변뿐만 아니라 쏘카가 있는 전국 어디서나 이용 가능해 출장 시에도 법인 차량을 이용할 수 있습니다. <br><br>'
	+'<br><br>'
	+'<strong> 쉽습니다! </strong><br><br>'
	+'온라인으로 구성원의 사용 내역 및 과금 현황 조회를 할 수 있어 비용처리 및 차량 배차 관리 등 업무용 차량 이용과 관리가 더욱 쉽고 편해집니다.</dd>'
	+'</dl>'
	+'</fieldset>'
	+'</form>'
	+'<div id="pagination" class="faq_pagination" style="margin-top: 15px;">'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>';

var customer_faq_6_form =
	'<div id= "customer" class="faq">'
	+'<div id="container" class="box">'
	+'<div id="content">'
	+'<h2><img src="'+app.img()+'/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
	+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
	+'<div class="faq_lnb">'
	+'<ul class="lnb faq_lnb">'
	+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
	+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
	+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
	+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
	+'</ul>'
	+'<div class="section1">'
	+'<h3><img src="http://socdnw.speedgabia.com/template/asset/images/customer/h3_faq.gif" alt="자주묻는 질문"></h3>'
	+'<div class="search-box">'
	+'<form class="faq_form" name="search" method="post" action="">'
	+'<fieldset>'
	+'<select>'
	+'<option selected="selected">전체</option>'
	+'</select>'
	+'<input type="text" class="input">'
	+'<input id="btn_search" type="image" class="submit" src="http://socdnw.speedgabia.com/template/asset/images/customer/btn_faq_search.gif" alt="검색">'
	+'</fieldset>'
	+'</form>'
	+'</div>'
	+'<form class="faq_form" name="faq" method="post" action="">'
	+'<fieldset>'
	+'<div class="tab">'
	+'<ul>'
	+'<li><a href="#" class="btn_category tab1 0">자주묻는 질문</a></li>'
	+'<li><a href="${context}/admin/faq_1" class="btn_category tab2 1">예약/결제문의</a></li>'
	+'<li><a href="${context}/admin/faq_2" class="btn_category tab3 2">가입문의</a></li>'
	+'<li><a href="${context}/admin/faq_3" class="btn_category tab4 3">차량이용/사고</a></li>'
	+'<li><a href="${context}/admin/faq_4" class="btn_category tab5 4">프로모션/쿠폰</a></li>'
	+'<li><a href="${context}/admin/faq_5" class="btn_category tab6 5">법인/단체</a></li>'
	+'<li class="on"><a href="${context}/admin/faq_6" class="btn_category tab7 6">탈퇴</a></li>'
	+'<li><a href="${context}/admin/faq_7" class="btn_category tab8 7">기타</a></li>'
	+'</ul>'
	+'</div>'
	 +'<p class="count">총게시물 <strong>3</strong>개</p>'
	+'<dl class="faq-list">'
	+'<dt name="#faq1" class="active"><span>Q</span> 탈퇴 시 보유한 크레딧은 환불이 되나요?</dt>'
	+'<dd style="display: block;"><span>A</span> 회사가 무상으로 부여한 크레딧은 환불되지 않습니다. 3개월 후 재가입을 하셔도 다시 생성되지 않습니다. 단, 유상으로 구매하신 크레딧은 규정에 따라 환불됩니다.</dd>'
	+'<dt name="#faq2"><span>Q</span> 탈퇴 시 재가입이 가능한가요?</dt>'
	+'<dd><span>A</span> 탈퇴 시 3개월간 재가입이 제한됩니다. 아이디/이름 변경 등이 필요한 경우에는 고객센터로 문의주세요.</dd>'
	+'<dt name="#faq3"><span>Q</span> 탈퇴를 하려면 어떻게 해야 하나요?</dt>'
	+'<dd><span>A</span> 쏘카 PC 홈페이지 로그인 후, 마이페이지&gt;내정보 하단의 탈퇴하기 버튼을 클릭하여, 탈퇴를 요청해주세요. 관리자가 미납 요금 및 환불 금액을 확인한 후 탈퇴를 처리해 드립니다.<br><br>'
	+'<br><br>'
	+'※ 모바일에서는 탈퇴 기능이 제공되지 않습니다. PC 홈페이지를 이용해 주세요.<br><br>'
	+'<br><br>'
	+'[!] 회원 탈퇴 시에는 아래의 주의 사항을 반드시 확인해주세요!<br><br>'
	+'1) 탈퇴 시 3개월간 재가입이 제한됩니다. 아이디/이름 변경 등이 필요한 경우에는 고객센터로 문의해주세요.<br><br>'
	+'2) 탈퇴 시 회사가 무상으로 부여한 크레딧은 환불되지 않으며, 3개월 후 재가입을 하셔도 다시 생성되지 않습니다. 단, 유상으로 구매하신 크레딧은 규정에 따라 환불해 드립니다.</dd>'
	+'</dl>'
	+'</fieldset>'
	+'</form>'
	+'<div id="pagination" class="faq_pagination" style="margin-top: 15px;">'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>';
	
var customer_faq_7_form =
	'<div id= "customer" class="faq">'
	+'<div id="container" class="box">'
	+'<div id="content">'
	+'<h2><img src="'+app.img()+'/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
	+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
	+'<div class="faq_lnb">'
	+'<ul class="lnb faq_lnb">'
	+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
	+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
	+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
	+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
	+'</ul>'
	+'<div class="section1">'
	+'<h3><img src="http://socdnw.speedgabia.com/template/asset/images/customer/h3_faq.gif" alt="자주묻는 질문"></h3>'
	+'<div class="search-box">'
	+'<form class="faq_form" name="search" method="post" action="">'
	+'<fieldset>'
	+'<select>'
	+'<option selected="selected">전체</option>'
	+'</select>'
	+'<input type="text" class="input">'
	+'<input id="btn_search" type="image" class="submit" src="http://socdnw.speedgabia.com/template/asset/images/customer/btn_faq_search.gif" alt="검색">'
	+'</fieldset>'
	+'</form>'
	+'</div>'
	+'<form class="faq_form" name="faq" method="post" action="">'
	+'<fieldset>'
	+'<div class="tab">'
	+'<ul>'
	+'<li><a href="#" class="btn_category tab1 0">자주묻는 질문</a></li>'
	+'<li><a href="${context}/admin/faq_1" class="btn_category tab2 1">예약/결제문의</a></li>'
	+'<li><a href="${context}/admin/faq_2" class="btn_category tab3 2">가입문의</a></li>'
	+'<li><a href="${context}/admin/faq_3" class="btn_category tab4 3">차량이용/사고</a></li>'
	+'<li><a href="${context}/admin/faq_4" class="btn_category tab5 4">프로모션/쿠폰</a></li>'
	+'<li><a href="${context}/admin/faq_5" class="btn_category tab6 5">법인/단체</a></li>'
	+'<li><a href="${context}/admin/faq_6" class="btn_category tab7 6">탈퇴</a></li>'
	+'<li class="on"><a href="${context}/admin/faq_7" class="btn_category tab8 7">기타</a></li>'
	+'</ul>'
	+'</div>'
	 +'<p class="count">총게시물 <strong>5</strong>개</p>'
	+'<dl class="faq-list">'
	+'<dt name="#faq1" class="active"><span>Q</span> 프로필 사진은 어떻게 변경하나요?</dt>'
	+'<dd style="display: block;"><span>A</span> 프로필 사진은 쏘친님께서 쏘카에 연동하신 SNS계정의 프로필 사진이 자동 연결되어 노출됩니다.<br><br>'
	+'따라서 쏘카 프로필 사진을 변경하시려면, 1. 연동하신 SNS계정의 프로필 사진을 변경하시고 2. 쏘카 앱 내정보 &gt; SNS계정 연동정보에서 연동을 해제하신 후 다시 연동해주셔야 합니다.<br><br>'
	+'혹시 그래도 프로필 사진이 쏘카 앱에 적용되지 않는 경우에는, 1. 사용 중이신 OS와 쏘카 앱을 최신버전으로 업데이트 하시고 2. 쏘카 앱, 그리고 SNS를 로그아웃 하신 후 다시 로그인 해주세요.</dd>'
	+'<dt name="#faq2"><span>Q</span> 세차가 하고 싶어요! 어떻게 해야하나요?</dt>'
	+'<dd><span>A</span> 이용 중 세차가 하고 싶으신가요? 자비부담으로 세차 진행 시 1만 크레딧으로 리워드 해드립니다. 이용 중인 차량의 스마트키 &gt; 추가 기능 사용하기 &gt; 세차 인증 메뉴에서 세차 전후 사진을 촬영하여 남겨주세요!<br><br>'
	+'※ 담당자 확인 후 크레딧 지급까지 3~4일이 소요됩니다.<br><br>'
	+'자세한 사항은 아래 링크를 참고하세요. <br><br>'
	+'<a href="http://www.socar.kr/notice/414#windowopen" style="color:blue;">☞ 세차리워드 안내 자세히 보기 (PC)</a></dd>'
	+'<dt name="#faq3"><span>Q</span> 회원카드 배송은 언제 되나요?</dt>'
	+'<dd><span>A</span> 회원카드 배송은 신청일로부터 주말/공휴일 제외 5~7일 정도 소요되며, 회원정보에 등록된 주소로 배송됩니다. 주소를 잘못 기입하여 반송되는 경우 추가 비용이 청구될 수 있으니, 반드시 우편물 수령이 가능한 주소를 입력해 주세요. <br><br>'
	+'※ 회원카드 신청 후 한달 이상 경과하여도 카드를 받지 못하셨다면, 고객센터(1661-3315)로 별도 문의해 주세요. <br><br>'
	+'※ 회원카드 수령과 관계없이 가입승인 후 모바일앱/웹 스마트키로 쏘카를 이용하실 수 있습니다.</dd>'
	+'<dt name="#faq4"><span>Q</span> 주변에 쏘카존이 없어서 이용이 불편합니다. 요청은 어떻게 하나요?</dt>'
	+'<dd><span>A</span> <div>원하시는 쏘카존이 있는 경우 자세한 위치 및 쏘카존이 생겼으면 하는 이유를 [쏘카 앱] 고객센터 &gt; 쏘카존 신청하기를 통해 알려주시면 의견을 수렴해 쏘카존을 마련해 나가도록 하겠습니다.&nbsp;</div>또는, Door to Door(D2D) 서비스를 이용하시면 원하는 위치로 쏘카가 배차되어 바로 차량 이용이 가능합니다.</dd>'
	+'<dt name="#faq5"><span>Q</span> 회원카드를 분실하면 어떻게 하나요?</dt>'
	+'<dd><span>A</span> 회원카드 분실 시에는 마이페이지 &gt; 내 정보 &gt; 차량제어수단 &gt; 추가 카드키 에서 재발급 신청을 해주세요. 재발급 비용은 1,500원입니다.<br><br>'
	+'<br><br>'
	+'안내사항<br><br>'
	+'- 회원카드가 반송되는 경우, 반송 및 재발송 비용은 본인 부담입니다.<br><br>'
	+'<br><br>'
	+'※ 회원카드 수령과 관계없이 가입승인 후 모바일앱/웹 스마트키로 쏘카를 이용하실 수 있습니다.</dd>'
	+'</dl>'
	+'</fieldset>'
	+'</form>'
	+'<div id="pagination" class="faq_pagination" style="margin-top: 15px;">'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>';

var customer_inquiry_form =
	'<div id= "customer" class="inquiry">'
	+'<div id="container" class="box">'
	+'<div id="content">'
	+'<h2><img src="'+app.img()+'/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
	+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
	+'<div class="faq_lnb">'
	+'<ul class="lnb faq_lnb">'
	+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
	+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
	+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
	+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
	+'</ul>'
	+'<div class="section1">'
	+'<h3><img src="http://socdnw.speedgabia.com/template/asset/images/customer/h3_inquiry.gif" alt="1:1 문의하기"></h3>'
	+'<form name="inquiry" method="post" accept-charset="utf-8" enctype="multipart/form-data">'
	+'<fieldset>'
	+'<table cellspacing="0" class="rows">'
	+'<tbody><tr>'
	+'<th><img src="http://socdnw.speedgabia.com/template/asset/images/customer/inquiry_txt2.gif" alt="문의분류"></th>'
	+'<td>'
	+'<select style="width:165px" name="category" id="category">'
	+'<option value="A">예약/결제문의</option>'
	+'<option value="B">가입문의</option>'
	+'<option value="C">차량이용/사고</option>'
	+'<option value="D">불편접수/건의</option>'
	+'<option value="E">프로모션/쿠폰</option>'
	+'<option value="H">법인/단체</option>'
	+'<option value="F">탈퇴</option>'
	+'<option value="I">쏘파라치</option>'
	+'<option value="G">기타</option>'
	+'</select>'
	+'</td>'
	+'</tr>'
	+'<tr>'
	+'<th><img src="http://socdnw.speedgabia.com/template/asset/images/customer/inquiry_txt3.gif" alt="제목 / 내용"></th>'
	+'<td>'
	+'<input id="title" type="text" name="title" class="input" value="" style="width:400px">'
	+'<textarea id="contents" cols="" name="contents" rows="15" class="textarea" style="width:585px"></textarea>'
	+'</td>'
	+'</tr>'
	+'<tr>'
	+'<th><img src="http://socdnw.speedgabia.com/template/asset/images/customer/inquiry_txt4.gif" alt="파일첨부"></th>'
	+'<td>'
	+'<input type="file" class="input" name="userfile" value="" style="height: 28px;">'
	+'<span class="tip ml10">이미지 파일은 jpg, png, gif 만 첨부가능합니다.</span>'
	+'</td>'
	+'</tr>'
	+'</tbody></table>'
	+'<p class="centerBtn">'
	+'<input type="submit" value="" class="btn_submit">'
	+'</p>'
	+'</fieldset>'
	+'</form>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>';

var customer_notice_content_form =
	'<div id= "customer" class="notice1">'
	+'<div id="container" class="box">'
	+'<div id="content">'
	+'<h2><img src="'+app.img()+'/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
	+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
	+'<div class="faq_lnb">'
	+'<ul class="lnb faq_lnb">'
	+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
	+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
	+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
	+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
	+'</ul>'
	+'<div class="section1">'
	+'<h3><img src="'+app.img()+'/h3_notice.gif" alt="공지사항"></h3>'
	+'<table cellspacing="0" summary="공지사항" class="cols">'
	+'<colgroup><col><col width="105"></colgroup>'
	+'<thead>'
	+'<tr>'
	+'<th>제목</th>'
	+'<th>작성일</th>'
	+'</tr>'
	+'</thead>'
	+'<tbody>'
	+'<tr>'
	+'<td id="notice_subj" class="subj">[공지] 매너평가 리뉴얼 : 평가 상벌제 안내</td>'
	+'<td>2016.10.11</td>'
	+'</tr>'
	+'</tbody>'
	+'</table>'
	+'<div class="viewCont">'
	+'<img src="http://www.socar.kr/uploads/ap6/notice/20161010/main_1714.jpg" width="500px"><br>'
	+'<br>'
	+'안녕하세요, 쏘카입니다.<br>'
	+'<br>'
	+'그동안 많은 쏘친들이 참여하고 피드백을 보내주셨던 ‘매너평가’<br>'
	+'쏘친들의 더욱 쾌적하고 즐거운 쏘카라이프를 위하여 새 단장하여 돌아왔습니다!<br>'
	+'<br>'
	+'다음 쏘친의 평가 피드백을 바탕으로 매너 있는 쏘친에게는 #매너뱃지를<br>'
	+'매너가 아쉬운 쏘친에게는 반납 상태를 돌아볼 수 있는 기회와 함께 <span style="color: blue;">#강력한벌점제운영</span>을 시작합니다.<br>'
	+'<br>'
	+'<br>'
	+'<strong>■ 매너평가 상벌제</strong><br>'
	+'<br>'
	+'평가 항목을 바탕으로 일정 횟수 누적 시 매너뱃지 혹은 이용 제재가 진행됩니다.<br>'
	+'· 평가 항목 : 행복해요, 흐뭇해요, 맘아파요 3가지 항목에 대한 평가 진행<br>'
	+'· 맘아파요 선택 시 상세 사유 선택 : 1.흡연 흔적 2.동물 털 3.쓰레기 4. 기타<br>'
	+'<br>'
	+'<strong>1) 매너 굿쏘친 임명 뱃지 부여</strong><br>'
	+'- 3명 이상의 쏘친들에게 행복한 반납 상태를 보여준 쏘친을 매너굿쏘친으로 임명!<br>'
	+'- 혜택 : 3회<img src="http://api1.socar.kr//uploads/ap2/badge/n_ico142.png" =""="" width="20px;">, 5회<img src="http://api1.socar.kr//uploads/ap2/badge/n_ico141.png" width="20px;">, 10회<img src="http://api1.socar.kr//uploads/ap2/badge/n_ico140.png" width="20px;"> 누적 시마다 금,은,동 매너 뱃지 발급 <span style="color: blue;">#MANNERS_MAKETH_MAN</span><br>'
	+'<br>'
	+'<strong>2) 매너가 아쉬운 쏘친은 이제 그만!</strong><br>'
	+'- 쏘친들! 다음 쏘친의 깨끗한 쏘카 탈 권리를 지켜주세요.<br>'
	+'내가 반납한 상태에 대하여 다음 쏘친의 매너평가와 신고된 사진을 기반으로 경고 및 제재 대상이 될 수 있습니다.<br>'
	+'- 내용 : 내부 정책에 따라 맘아파요를 5회 이상 받을 경우 쏘카 이용이 제한될 수 있습니다.<br>'
	 +'<span style="color: blue;">· 약 한 달간의 계도 기간을 거쳐, 11월 7일 이후 시행됩니다. (상세 내용 추후 공지)</span><br>'
	+'<br>'
	+'<br>'
	+'<strong>■ 매너평가 참여 방법</strong><br>'
	+'<br>'
	+'· 참여 방법 : 바로반납 시 이전 사용자의 반납 상태에 대한 의견을 남길 수 있습니다.<br>'
	+'이전 사용자 평가 전 나의 반납 상태를 되돌아보고, 놓고 내리는 소지품 없이 쾌적하게 반납해주세요!<br>'
	+'<br>'
	+'※ 참여를 놓쳤을 경우 [쏘카App 좌측 상단 메뉴 &gt; 고객센터 &gt; 매너평가]<br>'
	+'또는 알림센터에서 반납 시간 후 24시간 까지 참여 가능합니다.<br>'
	+'※ 맘아파요 선택 시에는 상세사유를 전달하게 됩니다.<br>'
	+'공정한 운영을 통하여 억울한 쏘친을 방지할 수 있도록 최대한 사진 첨부 부탁드립니다. <br>'
	+'<br>'
	+'· 나의 피평가 확인 방법 : [쏘카App 마이페이지 &gt; 프로필 &gt; 매너지수] 에서 직접 확인 가능합니다.<br>'
	+'<br>'
	+'<img src="http://www.socar.kr/uploads/ap6/notice/20161010/01_1627.jpg" width="200px">  <img src="http://www.socar.kr/uploads/ap6/notice/20161010/05_1743.jpg" width="200px">  <img src="http://www.socar.kr/uploads/ap6/notice/20161010/03_1628.jpg" width="200px"><br>'
	+'<br>'
	+'<br>'
	+'<strong>■ 쏘친의 깨끗한 쏘카 탈 권리</strong><br>'
	+'모두의 쾌적하고 즐거운 쏘카라이프를 위하여 지켜주세요!<br>'
	+'<br>'
	+'<strong>· 쏘카에서 흡연은 꼭 참아주세요!</strong><br>'
	+'함께 사용하는 분들을 위해 쏘카를 이용하는 동안 흡연은 꼭 참아주세요!<br>'
	+'이용 후에는 차량 내부에 있는 쓰레기를 정리해 주시기 바랍니다.<br>'
	+'<br>'
	+'<strong>※ 차량 내 흡연 적발 시 페널티 30만원 및 쏘카 이용이 영구 제한됩니다.</strong><br>'
	+'<a href="http://www.socar.kr/notice/510" target="_blank"><span style="color:blue;">☞담배와의 전쟁 상세보기</span></a><br>'
	+'<br>'
	+'<strong>· 애완동물은 캐리어를 이용해주세요!</strong><br>'
	+'애완동물은 캐리어를 이용해 쏘카에 동반 탑승하실 수 있습니다.<br>'
	+'단, 장애인 반려견은 캐리어 없이도 탑승 가능합니다.<br>'
	+'<br>'
	+'<strong>· 연료가 50%이상 남아있는지 확인해주세요!</strong><br>'
	+'다음 사용자를 위해 연료가 충분히 남았는지 확인해주세요.<br>'
	+'모든 주유소에서 주유가 가능하며, 결제는 차량 내부에 비치된 주유카드로 진행하시면 됩니다.<br>'
	+'<br>'
	+'<strong>· 이용 후 대여한 쏘카존으로 반납 필수!</strong><br>'
	+'편도 이용을 제외한 모든 차량 반납은 대여한 쏘카존으로 하셔야 합니다. <br>'
	+'만약 다른 차량이 주차되어 있거나 부득이한 사정이 생기신 경우는 고객센터로 연락주세요.<br>'
	+'<br>'
	+'<strong>· 반납시간을 준수해주세요!</strong><br>'
	+'다음 사용자를 위해 반납시간을 꼭 지켜주세요.<br>'
	+'반납이 늦어지는 경우 페널티 또는 경고 조치를 받을 수 있으며, 반납 연장은 모바일앱에서 가능합니다.<br>'
	+'<br>'
	+'<br>'
	+'<strong>■ 매너평가 Q&amp;A</strong><br>'
	+'<br>'
	+'<strong>Q. 먼저 탄 쏘친은 왜 평가하는 건가요?</strong><br>'
	+'쏘카는 여러 사람이 함께 이용하는 공유 자동차 입니다. <br>'
	+'다음 사용자를 위해서 내가 버린 쓰레기는 직접 치우고! 차량 내부에서 담배를 피우지 않고! <br>'
	+'깔끔하게 이용해 서로를 배려하자는 취지입니다.<br>'
	+'<br>'
	+'<strong>Q. 매너 평가는 언제 참여가능한가요?</strong><br>'
	+'[스마트키 &gt; 바로반납] 에서 참여 가능합니다.<br>'
	+'[쏘카App 좌측 상단 메뉴 &gt; 고객센터 &gt; 매너평가] 또는 알림센터에서 반납 시간 후 24시간 까지 참여 가능합니다.<br>'
	+'먼저 탄 쏘친의 머문자리를 잊어버리기 전에 재빠르게 참여해주세요:)<br>'
	+'<br>'
	+'<strong>Q. 평가는 꼭 해야 하는 건가요?</strong><br>'
	+'의무적인 것은 아니지만 보다 나은 쏘친의 차량 이용과 바람직한 공유문화 확산을 위해 꼭 참여해주세요. <br>'
	+'활발한 평가와 코멘트가 쏘카를 더욱 상쾌하게 만듭니다!<br>'
	+'<br>'
	+'<strong>Q. 제가 한 평가가 피평가자(먼저 탄 쏘친) 에게 전달이 되는 건가요?</strong><br>'
	+'평가결과는 먼저 탄 쏘친에게 전달되며,<br>'
	+'먼저 탄 쏘친이 [마이페이지 &gt; 프로필 &gt; 매너지수] 에서 직접 확인 가능합니다.<br>'
	+'<br>'
	+'<br>'
	+'무인 서비스이기 때문에 이용자 상호 간 매너 있는 이용이 중요한 `카셰어링`!<br>'
	+'모두가 잘타는 쏘카 라이프를 위하여 쏘친들의 적극적인 참여 부탁 드립니다.<br>'
	+'<br>'
	+'관련하여 궁금하신 사항은 아래의 설문으로 보내주세요!<br>'
	+'<a href="https://goo.gl/forms/wsDEh7KFLCIM6Uy82" target="_blank"><span style="color:blue;">☞매너평가 의견보내기</span></a><br>'
	+'<br>'
	+'☞ 쏘카 소식 보기<br>'
	+'ㄴ (페이스북) <a href="http://www.facebook.com/socarsharing#windowopen" target="_blank"><span style="color:blue;">http://www.facebook.com/socarsharing</span></a><br>'
	+'ㄴ (카카오톡) <span style="color: blue;">ID찾기 &gt; 쏘카 검색</span><br>'
	+'ㄴ (블로그) <a href="http://blog.socar.kr#windowopen" target="_blank"><span style="color:blue;">http://blog.socar.kr</span></a><br>'
	+'ㄴ (인스타그램) <a href="https://instagram.com/socarsharing#windowopen" target="_blank"><span style="color:blue;">https://instagram.com/socarsharing</span></a><br>'
	+'<br>'
	+'고맙습니다.<br>'
	+'타면된다, 쏘카!'
	+'<p class="centerBtn"><a href="#"><img src="http://socdnw.speedgabia.com/template/asset/images/common/btn_list.gif" alt="목록보기"></a></p>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>'
	+'</div>';
	
	var customer_notice_form =
		'<div id= "customer" class="notice1">'
		+'<div id="container" class="box">'
		+'<div id="content">'
		+'<h2><img src="resources/img/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
		+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
		+'<div class="faq_lnb">'
		+'<ul class="faq_lnb">'
		+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
		+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
		+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
		+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
		+'</ul>'
		+'<div class="section1">'
		+'<h3><img src="'+app.img()+'/h3_notice.gif" alt="공지사항"></h3>'
		+'<div class="notice-search">'
		+'<form name="search" method="post" action="">'
		+'<fieldset>'
		+'<input type="text" class="input">'
		+'<input id="btn_search" type="image" src="'+app.img()+'/btn_notice_search.gif" alt="검색">'
		+'</fieldset>'
		+'</form>'
		+'</div>'
		+'<table cellspacing="0" summary="공지사항" class="cols">'
		+'<colgroup><col width="65"><col><col width="105"></colgroup>'
		+'<thead>'
		+'<tr>'
		+'<th>번호</th>'
		+'<th>제목</th>'
		+'<th>작성일</th>'
		+'</tr>'
		+'</thead>'
		+'<tbody>'
		+'<tr>'
		+'<td>611</td>'
		+'<td class="subj"><a>[공지] 매너평가 리뉴얼 : 평가 상벌제 안내</a></td>'
		+'<td>2016.10.11</td>'
		+'</tr>'
		+'<tr>'
		+'<td>610</td>'
		+'<td class="subj"><a href="#_content">[쏘카존] 10월 3주 신규 쏘카존 오픈 안내</a></td>'
		+'<td>2016.10.11</td>'
		+'</tr>'
		+'<tr>'
		+'<td>609</td>'
		+'<td class="subj"><a href="#_content">[담배와의 전쟁] 쏘파라치 10월 1주차 적발 현황 공개</a></td>'
		+'<td>2016.10.07</td>'
		+'</tr>'
		+'<tr>'
		+'<td>608</td>'
		+'<td class="subj"><a href="#_content">[공지] 태풍 차바로 인한 울산, 제주지역 피해 복구 지원</a></td>'
		+'<td>2016.10.06</td>'
		+'</tr>'
		+'<tr>'
		+'<td>607</td>'
		+'<td class="subj"><a href="#_content">[쏘카존] 10월 2주 신규 쏘카존 오픈 안내</a></td>'
		+'<td>2016.10.05</td>'
		+'</tr>'
		+'<tr>'
		+'<td>606</td>'
		+'<td class="subj"><a href="#_content">[이벤트] 친구도 나도 2만원! 프렌즈 위크!</a></td>'
		+'<td>2016.10.05</td>'
		+'</tr>'
		+'<tr>'
		+'<td>605</td>'
		+'<td class="subj"><a href="#_content">[공지] 친구초대 쿠폰 지급조건 변경</a></td>'
		+'<td>2016.10.04</td>'
		+'</tr>'
		+'<tr>'
		+'<td>604</td>'
		+'<td class="subj"><a href="#_content">[담배와의 전쟁] 쏘파라치 9월 4주차 적발 현황 공개</a></td>'
		+'<td>2016.09.30</td>'
		+'</tr>'
		+'<tr>'
		+'<td>603</td>'
		+'<td class="subj"><a href="#_content">[쏘카] 안전운전캠페인 - 자동차 속도에 따른 충격과 피해 정도</a></td>'
		+'<td>2016.09.27</td>'
		+'</tr>'
		+'<tr>'
		+'<td>602</td>'
		+'<td class="subj"><a href="#_content">[이벤트] 가을맞이 깜짝 이벤트 (~10/7)</a></td>'
		+'<td>2016.09.26</td>'
		+'</tr>'
		+'</tbody>'
		+'</table>'
		+'<div class="paginate">'
		+'&nbsp;<strong>1</strong>&nbsp;<a href="">2</a>&nbsp;<a href="">3</a>&nbsp;<a href="">4</a>'
		+'&nbsp;<a href="">5</a>&nbsp;<a href="">6</a>&nbsp;<a href="">7</a>&nbsp;<a href="">8</a>'
		+'&nbsp;<a href="">9</a>&nbsp;<a href="">10</a>&nbsp;<a href="">11</a>'
		+'&nbsp;<a href="">&gt;</a>'
		+'</div>'
		+'</div>'
		+'</div>'
		+'</div>'
		+'</div>'
		+'</div>';
	
	var customer_voc_form =
		'<div id= "customer" class="voc">'
		+'<div id="container" class="box">'
		+'<div id="content">'
		+'<h2><img src="'+app.img()+'/h2.gif" alt="고객센터 쏘카에 대한 궁금증 해결을 도와드립니다."></h2>'
		+'<p class="callCenter"><img src="'+app.img()+'/btn_callcenter.gif" alt="콜센터 안내"></p>'
		+'<div class="faq_lnb">'
		+'<ul class="lnb faq_lnb">'
		+'<li><a href="#" title="공지사항" class="faq_lnb1">공지사항</a></li>'
		+'<li><a href="#" title="자주묻는 질문" class="faq_lnb2">자주묻는 질문</a></li>'
		+'<li><a href="#" title="1:1 문의하기" class="faq_lnb3">1:1 문의하기</a></li>'
		+'<li><a href="#" title="고객의견 반영절차" class="faq_lnb4">고객의견 반영절차</a></li>'
		+'</ul>'
		+'<div class="section1">'
		+'<h3><img src="http://socdnw.speedgabia.com/template/asset/images/customer/voc_title.png" alt="고객의견 반영절차"></h3>'
		+'<img src="http://socdnw.speedgabia.com/template/asset/images/customer/voc_contents.png?v=20160809" alt="고객의견 반영절차">'
		+'</div>'
		+'</div>'
		+'</div>'
		+'</div>'
		+'</div>';
	
	var fare_form =
		'<div id="container" class="box">'
		+'<div id="wrap">'
		+'<div id="container">'
		+'<div id="content">'
		+'<div class="index">'
		+'<img src="resources/img/fare/top_menu_img_2.png" alt="이용요금을 알려드립니다.">'
		+'</div>'
		+'<div class="box">'
		+'<div style="margin-top:30px;display:block;overflow:hidden;width:100%;">'
		+'<a href="https://goo.gl/QFGQtZ"><img src="resources/img/fare/banner_20160530.jpg" alt=""></a>'
		+'</div>'
		+'<div class="group">'
		+'<h3><img src="resources/img/fare/socarzone_drive_fee.png" alt="전국 쏘카존 대여요금 안내"></h3>'
		+'<p><img src="resources/img/fare/rental_txt14.gif" alt="타면된다, 쏘카!​ 10분단위로 자유롭게 신나는 드라이빙을 즐기세요! 다양한 쿠폰혜택과 모바일에서만 만나볼 수 있는 특가상품까지 부담없이 누리세요!"></p>'
		+'<table id="guide_table" cellspacing="0" class="cols">'
		+'<colgroup>'
		+'<col width="82">'
		+'<col width="172">'
		+'<col width="90">'
		+'<col width="90">'
		+'<col width="90">'
		+'<col width="110">'
		+'<col>'
		+'</colgroup>'
		+'<thead>'
		+'<tr>'
		+'<th rowspan="2">차종</th>'
		+'<th rowspan="2">모델</th>'
		+'<th rowspan="2">기준 대여요금<br>(10분기준)</th>'
		+'<th colspan="2">쏘친만을 위한 <span style="color:#f63325">특별할인!</span></th>'
		+'<th rowspan="2">주행요금<br>(주행거리 Km당)</th>'
		+'</tr>'
		+'<tr>'
		+'<th class="strong">주중</th>'
		+'<th>주말</th>'
		+'</tr>'
		+'</thead>'
		+'<tbody>'
		+'<tr>'
		+'<th rowspan="4" class="first">경형A<br></th>'
		+'<td class="tal">모닝</td>'
		+'<td>1,200원</td>'
		+'<td class="strong">720원~</td>'
		+'<td>960원~</td>'
		+'<td>160원</td>'
		+'</tr>'
		+'<tr>'
		+'<td class="tal">스파크</td>'
		+'<td>1,200원</td>'
		+'<td class="strong">720원~</td>'
		+'<td>960원~</td>'
		+'<td>160원</td>'
		+'</tr>'
		+'<tr>'
		+'<td class="tal">넥스트스파크</td>'
		+'<td>1,200원</td>'
		+'<td class="strong">720원~</td>'
		+'<td>960원~</td>'
		+'<td>160원</td>'
		+'</tr>'
		+'<tr>'
		+'<td class="tal">레이</td>'
		+'<td>1,250원</td>'
		+'<td class="strong">750원~</td>'
		+'<td>1,000원~</td>'
		+'<td>170원</td>'
		+'</tr>'
		+'<tr>'
		+'<th rowspan="2" class="first">소형</th>'
		+'<td class="tal">프라이드</td>'
		+'<td>1,430원</td>'
		+'<td class="strong">850원~</td>'
		+'<td>1,140원~</td>'
		+'<td>170원</td>'
		+'</tr>'
		+'<tr>'
		+'<td class="tal">엑센트</td>'
		+'<td>1,430원</td>'
		+'<td class="strong">850원~</td>'
		+'<td>1,140원~</td>'
		+'<td>170원</td>'
		+'</tr>'
		+'<tr>'
		+'<th rowspan="3" class="first">준중형</th>'
		+'<td class="tal">K3</td>'
		+'<td>1,580원</td>'
		+'<td class="strong">950원~</td>'
		+'<td>1,260원~</td>'
		+'<td>170원</td>'
		+'</tr>'
		+'<tr>'
		+'<td class="tal">아반떼</td>'
		+'<td>1,580원</td>'
		+'<td class="strong">950원~</td>'
		+'<td>1,260원~</td>'
		+'<td>170원</td>'
		+'</tr>'
		+'<tr>'
		+'<td class="tal">아반떼AD</td>'
		+'<td>1,580원</td>'
		+'<td class="strong">950원~</td>'
		+'<td>1,260원~</td>'
		+'<td>170원</td>'
		+'</tr>'
		+'<tr>'
		+'<th rowspan="5" class="first">중형</th>'
		+'<td class="tal">K5(LPG)</td>'
		+'<td>2,160원</td>'
		+'<td class="strong">1,300원~</td>'
		+'<td>1,730원~</td>'
		+'<td>140원</td>'
		+'</tr>'
		+'<tr>'
		+'<td class="tal">LF 쏘나타</td>'
		+'<td>2,160원</td>'
		+'<td class="strong">1,300원~</td>'
		+'<td>1,730원~</td>'
		+'<td>180원</td>'
		+'</tr>'
		+'<tr>'
		+'<td class="tal">LF 쏘나타(LPG)</td>'
		+'<td>2,160원</td>'
		+'<td class="strong">1,300원~</td>'
		+'<td>1,730원~</td>'
		+'<td>140원</td>'
		+'</tr>'
		+'<tr>'
		+'<td class="tal">SM5</td>'
		+'<td>2,160원</td>'
		+'<td class="strong">1,300원~</td>'
		+'<td>1,730원~</td>'
		+'<td>180원</td>'
		+'</tr>'
		+'<tr>'
		+'<td class="tal">말리부</td>'
		+'<td>2,660원</td>'
		+'<td class="strong">1,600원~</td>'
		+'<td>2,130원~</td>'
		+'<td>180원</td>'
		+'</tr>'
		+'</tbody>'
		+'</table>'
		+'<br>'
		+'<span style="color: #333">※ 주중/주말 기준</span>'
		+'<br>'
		+'<span style="color: #333">　·</span><span style="color: #333">주중 - 일 19:00 ~ 금 19:00 / 주중 심야 - 00:00 ~ 06:00</span>'
		+'<br>'
		+'<span style="color: #333">　·</span><span style="color: #333">주말 - 금 19:00 ~ 일 19:00 (공휴일 및 당사 지정 성수기 포함)</span>'
		+'<ul><br>'
		+'<li>요금표의 SO회원 특별할인 금액은 최저가 기준으로 지역마다 다를 수 있습니다.</li>'
		+'<li>대여요금은 지역별, 성수기/비수기 등에 따라 탄력요금제로 운영하므로, 위에 안내된 요금은 결제 시 요금과 다를 수 있습니다.</li>'
		+'<li>주행요금은 차량 이용 후 실제 주행거리에 따라 부과됩니다. 주행요금 계산기로 예상 비용을 미리 확인해보세요. <a href="#" class="oil">주행요금 계산기</a></li>'
		+'<li>편도/D2D(도어 투 도어) 서비스 이용 시에는 차량 회송비용 등을 고려한 별도 요금이 추가 과금될 수 있습니다.</li>'
		+'<li>대여요금 및 주행요금은 당사 내부정책/유가변동에 따라 변경될 수 있습니다.</li>'
		+'</ul>'
		+'</div>'
		+'</div>'
		+'</div>'
		+'</div>'
		+'</div>'
		+'</div>';
	
	var guide_form =
		'<div id="container" class="box">'
		+'<div id="content">'
		+'<div class="index">'
		+'<img src="resources/img/guide/top_menu_img_1.png" alt="쏘카에 대해 알아볼까요?">'
		+'</div>'
		+'<div class="guide_box1">'
		+'<div style="float: left;" class="snb">'
		+'<ul class="menu">'
		+'<li class="on"><a href="#socar1" class="menu1">이용방법</a></li>'
		+'<li><a href="#socar2" class="menu2">이용규칙</a></li>'
		+'<li><a href="#socar3" class="menu3">모바일 이용안내</a></li>'
		+'<li><a href="#socar4" class="menu4">쏘카 가이드</a></li>'
		+'<li><a href="#socar5" class="menu5">쏘카 임팩트</a></li>'
		+'</ul>'
		+'<ul class="banner">'
		+'<li><a href="https://www.facebook.com/socarsharing" target="_blank"><img src="resources/img/guide/banner1.gif" alt="쏘카 페이스북"></a></li>'
		+'<li><a href="http://blog.socar.kr" target="_blank"><img src="resources/img/guide/banner2_n.gif" alt="쏘카 블로그"></a></li>'
		+'<li><a href="https://goo.gl/Aqsjr5" target="_blank"><img src="resources/img/guide/banner3.gif" alt="쏘카 인재채용"></a></li>'
		+'</ul>'
		+'</div>'
		+'<div style="float: left; padding-left: 90px; width: 880px;" id="socar1" class="content">'
		+'<h3><img src="resources/img/guide/txt10.gif" alt="쏘카 이용방법"></h3>'
		+'<p class="txt"><img src="resources/img/guide/txt11.gif" alt="가입에서 예약 사용까지 간편하게 이용할 수 있는 편리하고 경제적인 쏘카의 이용방법을 알려드립니다. 쏘카와 함께 스마트 카셰어링을 경험해 보세요! "></p>'
		+'<ul>'
		+'<li class="rule1">'
		+'<h4><img src="resources/img/guide/txt12.gif" alt="회원 가입"></h4>'
		+'<p>카셰어링은 신뢰를 기반으로 한 회원제 서비스입니다.<br>'
		+'운전면허 및 결제카드 등록 후 SO회원이 되시면 쏘카 이용이 가능합니다.</p>'
		+'</li>'
		+'<li class="rule2">'
		+'<h4><img src="resources/img/guide/txt13.gif" alt="차량 예약"></h4>'
		+'<p>SO회원 가입 승인 후 쏘카 예약이 가능합니다. 홈페이지 및 모바일앱을 이용해 예약하실<br>수 있고 정상적으로 예약완료된 경우 휴대폰으로 확인메시지가 전송됩니다.</p>'
		+'<p>'
		+'<img src="resources/img/guide/mobile.gif" alt="안드로이드폰, 아이폰" usemap="#mobile.gif">'
		+'<map name="mobile.gif">'
		+'<area shape="rect" coords="1,0,98,23" href="https://play.google.com/store/apps/details?id=socar.Socar&amp;utm_source=www-socar&amp;utm_medium=guide" target="_blank" alt="안드로이드폰">'
		+'<area shape="rect" coords="99,0,166,23" href="https://itunes.apple.com/kr/app/id515173864" target="_blank" alt="아이폰">'
		+'</map>'
		+'</p>'
		+'</li>'
		+'<li class="rule3">'
		+'<h4><img src="resources/img/guide/txt14.gif" alt="쏘카 이용"></h4>'
		+'<p>쏘카앱 스마트키 잠금해제 버튼을 누르거나, 등록한 회원카드를 차량 앞 유리에 부착된 단말기에 접촉시켜 주세요. 경적음이 울린 후 차량 문이 열립니다.<br> 예약한 시간 동안에는 회원카드 및 모바일앱 스마트키로 차량 문을 제어할 수 있습니다.</p>'
		+'</li>'
		+'<li class="rule4">'
		+'<h4><img src="resources/img/guide/txt15.gif" alt="차량 반납"></h4>'
		+'<p>반납 시간에 맞추어 차량을 반납 장소에 주차하신 후 모바일앱 스마트키 및 회원카드로 차량 문을 <br>잠가 주세요.<br>'
		+'제자리에 정상 반납 처리되면 휴대폰으로 확인 메시지가 발송됩니다.</p>'
		+'</li>'
		+'<li class="rule5">'
		+'<h4><img src="resources/img/guide/txt16.gif" alt="요금 결제"></h4>'
		+'<p>차량 이용에 따른 요금은 대여료와 주행요금으로 구분되며, 가입시 등록한 결제카드로 청구됩니다.<br>'
		+'결제가 완료되지 않으면 차량 사용에 제한이 있을 수 있으니, 미리 결제카드의 유효여부를<br>확인해주세요. </p>'
		+'</li>'
		+'</ul>'
		+'</div>'
		+'</div>'
		+'</div>'
		+'</div>'
		+'</div>';
	
var company_form =
     '<div id="container" class="box">'
     +'<div id="content">'
     +'<div class="index">'
     +'<img src="resources/img/company/top_menu_img_3.png" alt="법인/단체 프로그램을 알아보세요!">'
     +'</div>'
     +'<div class="box">'
     +'<div style="float: left;" class="snb">'
     +'<ul class="menu">'
     +'<li class="on"><a href="#company1" class="menu1">프로그램안내 및 혜택</a></li>'
     +'<li><a href="#company2" class="menu2">가입 및 이용 방법</a></li>'
     +'<li><a href="#company3" class="menu3">자주 묻는 질문</a></li>'
     +'</ul>'
     +'<ul class="banner">'
     +'<li><a href="https://www.facebook.com/socarsharing" target="_blank"><img src="http://socdnw.speedgabia.com/template/asset/images/socar/banner1.gif" alt="쏘카 페이스북"></a></li>'
     +'<li><a href="http://blog.socar.kr" target="_blank"><img src="http://socdnw.speedgabia.com/template/asset/images/socar/banner2_new.gif" alt="쏘카 블로그"></a></li>'
     +'<li><a href="https://goo.gl/Aqsjr5" target="_blank"><img src="http://socdnw.speedgabia.com/template/asset/images/socar/banner3.gif" alt="쏘카 인재채용"></a></li>'
     +'</ul>'
     +'</div>'
     +'<div style="float: left; padding-left: 90px; width: 880px;" id="company1" class="content">'
     +'<h3><img src="resources/img/company/txt4.gif" alt="쏘카 법인/단체 프로그램"></h3>'
     +'<p class="txt"><img src="resources/img/company/txt5.gif" alt="쏘카 법인/단체 프로그램은 1인 이상의 기업, 정부기관, 비영리단체를 대상으로 진행하는 특별 프로그램입니다. 쏘카는 법인/단체의 비용 절감 및 간편한 이용을 통해 업무 효율성을 높이는 등 최상의 업무 차량 지원을 제공합니다."></p>'
     +'<div><a href="/join"><img alt="법인/단체 회원가입" src="resources/img/company/btn_company_mail_n.gif"></a><a href="https://www.dropbox.com/sh/nbmi016ck6bihl9/AAC1mnZNR3-vqe5ww6tcxZr1a?dl=0" target="_blank" style="margin-left:10px;"><img alt="법인 프로그램안내서 다운로드" src="http://socdnw.speedgabia.com/template/asset/images/company/btn_company.gif"></a></div>'
     +'<div style="margin-top:20px;">'
     +'<iframe width="560" height="315" src="//www.youtube.com/embed/ed3GNGmpidc" frameborder="0" allowfullscreen=""></iframe>'
     +'</div>'
     +'</div>'
     +'</div>';